### ISSUE TITLE
Shortcode is not working

### ISSUE THREAD

**Issue by nikunj1990** [webwizo/laravel-shortcodes#3]
Hello,
I have followed all steps. and I used Shortcode::compile($page->contents); in view file it's not working and displaying shortcode.

When I using this return view('pages.show')->withShortcodes('page',$page); code in controller it generating errors.

And Can you please suggest when I put this code "$shortcode = app('shortcode');" ?
I created ioc.php and put this code but it's generating errors.

Please suggest me. And thanks for this latest shortcode library...

**Comment by webwizo** [comment]
Hey,

If you setup a Alias for Shortcodes as per the documentation, You can use following code:
`{{ \Shortcode::compile($page->contents) }}`

second, you wrote `view('pages.show')->withShortcodes('page',$page);` but it is not the right way to do it.

Do as following code:
`return view('pages.show')->with('page', $page)->withShortcodes();`

->withShortcodes() you just have to mention it so that view would be compile automatically.

I don't know how you use the ioc.php file, I use `$shortcode = app('shortcode')` whenever I don't want to use Facades.

I hope it would be helpful.

**Comment by nikunj1990** [comment]
Thank you Asif for reply.
But still shortcode not working...

When I write `{{\Shortcode::compile('this is testing [b class="test"]test[/b]')}}`  in my view file I am getting below output:
"this is testing [b class="test"]test[/b]"

Please help me for resolve this issue....
Thanks again

**Comment by webwizo** [comment]
Please see attached code, as I have written your code and got the result.

[Result Image](http://www.screencast.com/t/ANBS8HmwRCAO)

**Comment by nikunj1990** [comment]
![untitled-1_01](https://cloud.githubusercontent.com/assets/14015105/17737630/7f4835c4-64ab-11e6-859f-145896bf63ce.jpg)

Hello,
Please see this image... 

I have changed return output in BoldShortcode.php but it is not working...

**Comment by webwizo** [comment]
Alright, have you added `ShortcodesServiceProvider` into `app/config/app.php` providers array?

**Comment by nikunj1990** [comment]
yes I have put Webwizo\Shortcodes\ShortcodesServiceProvider::class code on app.php

and aliases 'Shortcode' => Webwizo\Shortcodes\Facades\Shortcode::class paste... :)

**Comment by webwizo** [comment]
No, not that one.

You have created your own ShortcodesServiceProvider which is `App\Providers\ShortcodesServiceProvider::class` this provider you need to put into app.php file.

**Comment by webwizo** [comment]
![2016-08-18_13-11-30](https://cloud.githubusercontent.com/assets/1593953/17766624/75e207cc-6545-11e6-9c5d-04b908616110.jpg)

See the above code.

**Comment by nikunj1990** [comment]
Yes,

I have already added App\Providers\ShortcodesServiceProvider::class to the providers lists in app.php but I got such kind of the error...please see screenshot...http://screencast.com/t/9qHRw2ew

**Comment by webwizo** [comment]
Dear,

As per your screenshot, you have provided a your class correctly, but in `ShortcodesServiceProvider.php` class file, you have mentioned wrong Namespace, I guess.

Can you please replace `App\Providers` instead of `App\Providers\Shortcode` in `ShortcodesServiceProvider.php` file?

Let me know, if you get same error or share a code with me of your file `ShortcodesServiceProvider.php`

Thanks,

**Comment by asimshazad** [comment]
Hello webwizo,
Thank you for this awesome package.
I am having a little issue while using this.

**Service provider array**

 Webwizo\Shortcodes\ShortcodesServiceProvider::class,
App\Providers\ShortcodesServiceProvider::class

**Custom Controller Method**

public function getPage($slug)
    {
        $page = Page::whereSlug($slug)->first();
        return view('front.pages.index',compact('page'))->withShortcodes();
    }

I am using prebuilt BoldShortcode class,How can i use the shortcode in view to  get the bold string.
This is how i am trying to implement this in view

[b class="test"]test[/b]

But getting this error

Missing argument 5 for App\Shortcodes\BoldShortcode::register()

**Comment by webwizo** [comment]
Asim. Let me fix the issue. It is a 5 argument issue which was being added by one contributor and didn’t update the documentation properly.

**Comment by denmaz** [comment]
I am not sure if this suggestion is correct or not.
but I think the argument 5 is view variable so I do as below, so that view variables can be accessed from custome shortcode:

on namespace Webwizo\Shortcodes\View@renderContents => $contents = $this->shortcode->viewData($this->getData())->compile($contents);


on namespace Webwizo\Shortcodes\Compilers;

class ShortcodeCompiler
{
	
	protected $_viewData;
    
	public function viewData( $viewData )
    {
        $this->_viewData = $viewData;
		return $this;
    }
	
	
	
	public function render($matches)
    {
        // Compile the shortcode
        $compiled = $this->compileShortcode($matches);
        $name = $compiled->getName();
		$viewData = $this->_viewData;

        // Render the shortcode through the callback
        return call_user_func_array($this->getCallback($name), [
            $compiled,
            $compiled->getContent(),
            $this,
            $name,
			$viewData
        ]);
    }
}

**Comment by kutung** [comment]
Can you update this fix in the current version.

**Comment by professorhaseeb** [comment]
any updates on the 5th missinng param?

**Comment by professorhaseeb** [comment]
@kutung this fix works,

**Comment by Hammad-XT** [comment]
Shorcode display alignment issue here is my html 

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. 

**[most-popular-resturants]**

It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.

**[xmas-bg-600-dark city="la"]**


In this html 2 shortcode here

- [most-popular-resturants] 
- [xmas-bg-600-dark city="la"]


When i run this method (Shortcode::compile($htmlContent)) result perfectly display but shortcode first render and after html display 


![image](https://user-images.githubusercontent.com/81748038/140881229-6f2dc708-f276-46c2-9c75-6d469578d549.png)


I want display result to specific short code position in html. give me a solution thanks. 

Urgent required.
